theme: minima
title: Luke Statler
author: Luke Statler
email: lstats99@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  University of Iowa
    - M.S. Business Analytics
    - B.S. Sport and Recreation Management
    - B.A. Informatics

# social links
twitter_username: stat_machine # DO NOT include the @ character, or else the build will fail!
github_username:  lstatler # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
